import { LANGUAGES, SUPPORTED_LANGS, type LanguageCode } from "@holi/configs/i18n";

export const languages = LANGUAGES;
export type ImageLanguage = LanguageCode;
type Mode = "optimize" | "resize" | "crop" | "convert" | "clean";
type Fact = readonly [string, string, "local" | "connected"];

export interface ImageCopy {
  title: string; description: string; eyebrow: string; headline: string; intro: string; localBadge: string;
  workspaceLabel: string; dropTitle: string; dropHelp: string; chooseImages: string; supported: string;
  files: string; clear: string; emptyQueue: string; original: string; result: string; previewEmpty: string;
  modes: Record<Mode, { label: string; description: string }>;
  quality: string; width: string; height: string; lockRatio: string; cropRatio: string; format: string;
  originalFormat: string; reset: string; downloadCurrent: string; downloadAll: string;
  ready: string; processing: string; failed: string; cleanNote: string; sourceLabel: string; outputLabel: string;
  privacyTitle: string; privacySummary: string; details: string; privacyFacts: readonly Fact[];
  explainerTitle: string; explainer: string; features: readonly (readonly [string, string])[];
  faqTitle: string; faqs: readonly (readonly [string, string])[];
  privacyPageTitle: string; privacyPageIntro: string; privacySections: readonly (readonly [string, string])[]; back: string;
}

const copy: Record<ImageLanguage, ImageCopy> = {
  en: {
    title: "Holi Image — private image workspace", description: "Optimize, resize, crop, convert, and remove copied metadata from images locally in your browser.",
    eyebrow: "One workspace · five operations", headline: "Shape images without handing them over.", intro: "Open several images, adjust them in one calm workspace, compare the result, and export only when you are ready.", localBadge: "Local processing",
    workspaceLabel: "Image workspace", dropTitle: "Drop images here", dropHelp: "They stay in this browser tab. Nothing is uploaded when you choose a file.", chooseImages: "Choose images", supported: "JPEG, PNG, and WebP · multiple files welcome", files: "Images", clear: "Clear", emptyQueue: "Your image queue is empty.", original: "Original", result: "Result", previewEmpty: "Choose an image to start comparing.",
    modes: { optimize: { label: "Optimize", description: "Balance visual quality and file size." }, resize: { label: "Resize", description: "Set exact pixel dimensions." }, crop: { label: "Crop", description: "Center-crop to a useful aspect ratio." }, convert: { label: "Convert", description: "Export as JPEG, PNG, or WebP." }, clean: { label: "Clean", description: "Create a fresh pixel-only export." } },
    quality: "Quality", width: "Width", height: "Height", lockRatio: "Keep aspect ratio", cropRatio: "Crop ratio", format: "Output format", originalFormat: "Keep original", reset: "Reset settings", downloadCurrent: "Download image", downloadAll: "Download all (.zip)", ready: "Ready", processing: "Processing…", failed: "This image could not be processed.", cleanNote: "Every export is newly encoded from pixels. Holi does not copy EXIF, GPS, comments, or the original filename into it.", sourceLabel: "Source", outputLabel: "Export",
    privacyTitle: "Privacy summary", privacySummary: "Images are processed in this browser. Cloudflare can observe your IP address and access time, but Holi does not upload the images you open.", details: "Privacy details", privacyFacts: [["Images", "Opened images and previews stay in this tab's memory.", "local"], ["Processing", "Resize, crop, conversion, and encoding run through browser image APIs.", "local"], ["Downloads", "A file leaves the workspace only when you explicitly download it.", "local"], ["Hosting", "Cloudflare may process IP, request time, requested path, traffic volume, and routing data.", "connected"]],
    explainerTitle: "A single image tool, not a maze of tiny utilities", explainer: "The operations share the same queue, preview, settings, and export pipeline. You do not need to reopen the same file on separate pages.", features: [["Optimize and compare", "Tune lossy quality while seeing the new size before download."], ["Resize and crop", "Keep proportions or use centered square, portrait, landscape, and widescreen crops."], ["Convert and clean", "Create JPEG, PNG, or WebP files without copying source metadata blocks."]],
    faqTitle: "Common questions", faqs: [["Are my images uploaded?", "No. Selecting, dropping, editing, and encoding happen in the browser. Cloudflare still receives ordinary connection metadata when serving the page."], ["Does Clean erase every possible trace?", "Holi exports newly encoded pixels and does not copy source metadata. The visual pixels can still contain identifying information."], ["Why is the exported size sometimes larger?", "PNG is lossless and photos can grow. JPEG or WebP with lower quality is usually smaller for photography."]],
    privacyPageTitle: "Privacy in Holi Image", privacyPageIntro: "This is the implemented data flow for the image workspace.", privacySections: [["Input and memory", "Chosen files are decoded in this tab and held in volatile memory. Holi does not send file bytes, filenames, previews, or settings to a server."], ["Output and metadata", "Exports are newly encoded from canvas pixels. EXIF, GPS, comments, thumbnails, and filenames are not copied. Visible information inside the pixels remains."], ["Browser storage", "Images are not persisted. Shared theme and language preferences may remain in local browser storage."], ["Network and provider", "Loading this static application reaches Cloudflare, which can process IP address, time, requested path, traffic volume, and routing or security metadata."]], back: "Back to Holi Image",
  },
  es: {
    title: "Holi Image — espacio privado de imágenes", description: "Optimiza, redimensiona, recorta, convierte y evita copiar metadatos de imágenes localmente en tu navegador.", eyebrow: "Un espacio · cinco operaciones", headline: "Transforma imágenes sin entregarlas.", intro: "Abre varias imágenes, ajústalas en un espacio tranquilo, compara el resultado y exporta solo cuando esté listo.", localBadge: "Procesamiento local",
    workspaceLabel: "Espacio de imágenes", dropTitle: "Suelta imágenes aquí", dropHelp: "Permanecen en esta pestaña. Elegir un archivo no lo sube a ningún servidor.", chooseImages: "Elegir imágenes", supported: "JPEG, PNG y WebP · puedes elegir varias", files: "Imágenes", clear: "Limpiar", emptyQueue: "Tu lista de imágenes está vacía.", original: "Original", result: "Resultado", previewEmpty: "Elige una imagen para empezar a comparar.",
    modes: { optimize: { label: "Optimizar", description: "Equilibra calidad visual y tamaño." }, resize: { label: "Redimensionar", description: "Define dimensiones exactas en píxeles." }, crop: { label: "Recortar", description: "Recorta al centro con una proporción útil." }, convert: { label: "Convertir", description: "Exporta como JPEG, PNG o WebP." }, clean: { label: "Limpiar", description: "Crea una exportación nueva de solo píxeles." } },
    quality: "Calidad", width: "Ancho", height: "Alto", lockRatio: "Conservar proporción", cropRatio: "Proporción de recorte", format: "Formato de salida", originalFormat: "Conservar original", reset: "Restablecer ajustes", downloadCurrent: "Descargar imagen", downloadAll: "Descargar todas (.zip)", ready: "Listo", processing: "Procesando…", failed: "No se pudo procesar esta imagen.", cleanNote: "Cada exportación se codifica de nuevo desde los píxeles. Holi no copia EXIF, GPS, comentarios ni el nombre original.", sourceLabel: "Origen", outputLabel: "Exportación",
    privacyTitle: "Resumen de privacidad", privacySummary: "Las imágenes se procesan en este navegador. Cloudflare puede conocer tu IP y horario de acceso, pero Holi no sube las imágenes que abres.", details: "Detalles de privacidad", privacyFacts: [["Imágenes", "Las imágenes abiertas y vistas previas permanecen en la memoria de esta pestaña.", "local"], ["Procesamiento", "Redimensionar, recortar, convertir y codificar usa las API del navegador.", "local"], ["Descargas", "Un archivo sale del espacio solo cuando tú lo descargas.", "local"], ["Alojamiento", "Cloudflare puede procesar IP, horario, ruta solicitada, volumen y enrutamiento.", "connected"]],
    explainerTitle: "Una herramienta de imágenes, no un laberinto de miniutilidades", explainer: "Las operaciones comparten lista, vista previa, ajustes y exportación. No necesitas abrir el mismo archivo en varias páginas.", features: [["Optimiza y compara", "Ajusta la calidad viendo el nuevo tamaño antes de descargar."], ["Redimensiona y recorta", "Conserva proporciones o usa recortes cuadrados, verticales, horizontales y panorámicos."], ["Convierte y limpia", "Crea JPEG, PNG o WebP sin copiar bloques de metadatos del origen."]],
    faqTitle: "Preguntas frecuentes", faqs: [["¿Se suben mis imágenes?", "No. Seleccionar, soltar, editar y codificar ocurre en el navegador. Cloudflare sí recibe metadatos normales al servir la página."], ["¿Limpiar borra cualquier rastro?", "Holi codifica píxeles nuevos y no copia metadatos. Los píxeles visibles aún pueden mostrar información identificable."], ["¿Por qué a veces pesa más?", "PNG no tiene pérdida y una foto puede crecer. JPEG o WebP con menor calidad suele pesar menos."]],
    privacyPageTitle: "Privacidad en Holi Image", privacyPageIntro: "Este es el flujo de datos implementado en el espacio de imágenes.", privacySections: [["Entrada y memoria", "Los archivos se decodifican en esta pestaña y quedan en memoria volátil. Holi no envía bytes, nombres, vistas previas ni ajustes a un servidor."], ["Salida y metadatos", "Las exportaciones se codifican desde píxeles del canvas. No se copian EXIF, GPS, comentarios, miniaturas ni nombres; la información visible permanece."], ["Almacenamiento", "Las imágenes no se conservan. Las preferencias compartidas de tema e idioma pueden quedar en almacenamiento local."], ["Red y proveedor", "Cargar esta aplicación estática contacta a Cloudflare, que puede procesar IP, hora, ruta, volumen y metadatos de seguridad o enrutamiento."]], back: "Volver a Holi Image",
  },
  zh: {
    title: "Holi Image — 私密图像工作区", description: "在浏览器本地优化、调整大小、裁剪、转换图像，并避免复制元数据。", eyebrow: "一个工作区 · 五种操作", headline: "处理图像，不必交出图像。", intro: "一次打开多张图像，在同一工作区调整和比较，准备好后再导出。", localBadge: "本地处理", workspaceLabel: "图像工作区", dropTitle: "将图像拖到这里", dropHelp: "图像只保留在此标签页；选择文件不会上传。", chooseImages: "选择图像", supported: "JPEG、PNG、WebP · 支持多选", files: "图像", clear: "清空", emptyQueue: "图像队列为空。", original: "原图", result: "结果", previewEmpty: "选择图像开始比较。",
    modes: { optimize: { label: "优化", description: "平衡画质与文件大小。" }, resize: { label: "调整大小", description: "设置精确像素尺寸。" }, crop: { label: "裁剪", description: "按常用比例居中裁剪。" }, convert: { label: "转换", description: "导出 JPEG、PNG 或 WebP。" }, clean: { label: "清理", description: "创建全新像素导出。" } }, quality: "质量", width: "宽度", height: "高度", lockRatio: "保持比例", cropRatio: "裁剪比例", format: "输出格式", originalFormat: "保持原格式", reset: "重置设置", downloadCurrent: "下载图像", downloadAll: "下载全部（.zip）", ready: "就绪", processing: "处理中…", failed: "无法处理此图像。", cleanNote: "每次导出都从像素重新编码。Holi 不会复制 EXIF、GPS、注释或原文件名。", sourceLabel: "来源", outputLabel: "导出",
    privacyTitle: "隐私摘要", privacySummary: "图像在此浏览器处理。Cloudflare 可能看到 IP 和访问时间，但 Holi 不上传你打开的图像。", details: "隐私详情", privacyFacts: [["图像", "打开的图像和预览保留在此标签页内存中。", "local"], ["处理", "缩放、裁剪、转换和编码使用浏览器图像 API。", "local"], ["下载", "只有你明确下载时文件才离开工作区。", "local"], ["托管", "Cloudflare 可处理 IP、请求时间、路径、流量和路由数据。", "connected"]],
    explainerTitle: "一个图像工具，而不是迷宫般的小工具", explainer: "所有操作共享队列、预览、设置和导出流程，无需在不同页面重复打开文件。", features: [["优化并比较", "下载前调整质量并查看新文件大小。"], ["缩放与裁剪", "保持比例，或使用方形、竖向、横向和宽屏裁剪。"], ["转换并清理", "生成 JPEG、PNG 或 WebP，不复制来源元数据。"]], faqTitle: "常见问题", faqs: [["图像会上传吗？", "不会。选择、拖放、编辑和编码都在浏览器完成；Cloudflare 会收到页面的普通连接元数据。"], ["清理能消除所有痕迹吗？", "Holi 重新编码像素且不复制源元数据，但像素本身仍可能含可识别信息。"], ["为什么导出有时更大？", "PNG 无损，照片可能变大；较低质量的 JPEG 或 WebP 通常更小。"]],
    privacyPageTitle: "Holi Image 隐私", privacyPageIntro: "这是图像工作区实际实现的数据流。", privacySections: [["输入与内存", "文件在此标签页解码并保存在易失内存中，不向 Holi 服务器发送字节、文件名、预览或设置。"], ["输出与元数据", "导出从画布像素重新编码，不复制 EXIF、GPS、注释、缩略图或文件名；可见像素中的信息仍会保留。"], ["浏览器存储", "工作区不保存图像；主题和语言偏好可能保存在本地存储中。"], ["网络与提供商", "加载静态应用会访问 Cloudflare；其可处理 IP、时间、路径、流量和路由或安全元数据。"]], back: "返回 Holi Image",
  },
  hi: {
    title: "Holi Image — निजी इमेज वर्कस्पेस", description: "ब्राउज़र में इमेज ऑप्टिमाइज़, रीसाइज़, क्रॉप, कन्वर्ट और मेटाडेटा कॉपी किए बिना एक्सपोर्ट करें।", eyebrow: "एक वर्कस्पेस · पाँच काम", headline: "इमेज सँवारें, उन्हें सौंपें नहीं।", intro: "कई इमेज खोलें, एक जगह तुलना करें और तैयार होने पर ही एक्सपोर्ट करें।", localBadge: "लोकल प्रोसेसिंग", workspaceLabel: "इमेज वर्कस्पेस", dropTitle: "इमेज यहाँ छोड़ें", dropHelp: "वे इसी टैब में रहती हैं; चुनने पर अपलोड नहीं होतीं।", chooseImages: "इमेज चुनें", supported: "JPEG, PNG और WebP · कई फ़ाइलें", files: "इमेज", clear: "साफ़ करें", emptyQueue: "इमेज सूची खाली है।", original: "मूल", result: "परिणाम", previewEmpty: "तुलना के लिए इमेज चुनें।",
    modes: { optimize: { label: "ऑप्टिमाइज़", description: "गुणवत्ता और आकार में संतुलन।" }, resize: { label: "रीसाइज़", description: "सटीक पिक्सेल आकार तय करें।" }, crop: { label: "क्रॉप", description: "उपयोगी अनुपात में केंद्र से काटें।" }, convert: { label: "कन्वर्ट", description: "JPEG, PNG या WebP एक्सपोर्ट।" }, clean: { label: "क्लीन", description: "नई केवल-पिक्सेल कॉपी बनाएँ।" } }, quality: "गुणवत्ता", width: "चौड़ाई", height: "ऊँचाई", lockRatio: "अनुपात रखें", cropRatio: "क्रॉप अनुपात", format: "आउटपुट फ़ॉर्मेट", originalFormat: "मूल रखें", reset: "सेटिंग रीसेट", downloadCurrent: "इमेज डाउनलोड", downloadAll: "सभी डाउनलोड (.zip)", ready: "तैयार", processing: "प्रोसेस हो रहा है…", failed: "इमेज प्रोसेस नहीं हो सकी।", cleanNote: "हर एक्सपोर्ट पिक्सेल से दोबारा एनकोड होता है। Holi EXIF, GPS, टिप्पणी या मूल नाम कॉपी नहीं करता।", sourceLabel: "स्रोत", outputLabel: "एक्सपोर्ट",
    privacyTitle: "गोपनीयता सारांश", privacySummary: "इमेज इसी ब्राउज़र में प्रोसेस होती हैं। Cloudflare IP और समय देख सकता है, पर Holi इमेज अपलोड नहीं करता।", details: "गोपनीयता विवरण", privacyFacts: [["इमेज", "इमेज और प्रीव्यू इस टैब की मेमोरी में रहते हैं।", "local"], ["प्रोसेसिंग", "रीसाइज़, क्रॉप, कन्वर्ज़न और एनकोडिंग ब्राउज़र API से होते हैं।", "local"], ["डाउनलोड", "आपके डाउनलोड करने पर ही फ़ाइल बाहर जाती है।", "local"], ["होस्टिंग", "Cloudflare IP, समय, पथ, ट्रैफ़िक और रूटिंग डेटा प्रोसेस कर सकता है।", "connected"]],
    explainerTitle: "छोटे टूल्स की भूलभुलैया नहीं, एक इमेज टूल", explainer: "सभी काम एक ही सूची, प्रीव्यू, सेटिंग और एक्सपोर्ट पाइपलाइन साझा करते हैं।", features: [["ऑप्टिमाइज़ और तुलना", "डाउनलोड से पहले गुणवत्ता और नया आकार देखें।"], ["रीसाइज़ और क्रॉप", "अनुपात रखें या वर्ग, पोर्ट्रेट, लैंडस्केप और वाइडस्क्रीन क्रॉप चुनें।"], ["कन्वर्ट और क्लीन", "स्रोत मेटाडेटा के बिना JPEG, PNG या WebP बनाएँ।"]], faqTitle: "आम सवाल", faqs: [["क्या इमेज अपलोड होती हैं?", "नहीं। चुनाव, ड्रॉप, एडिट और एनकोड ब्राउज़र में होते हैं; Cloudflare सामान्य कनेक्शन मेटाडेटा पाता है।"], ["क्या Clean हर निशान हटाता है?", "Holi स्रोत मेटाडेटा कॉपी नहीं करता; दृश्य पिक्सेल में पहचान योग्य जानकारी रह सकती है।"], ["फ़ाइल कभी बड़ी क्यों होती है?", "PNG lossless है; फोटो के लिए कम गुणवत्ता वाला JPEG या WebP प्रायः छोटा होता है।"]],
    privacyPageTitle: "Holi Image में गोपनीयता", privacyPageIntro: "यह इमेज वर्कस्पेस का लागू डेटा प्रवाह है।", privacySections: [["इनपुट और मेमोरी", "फ़ाइलें इसी टैब में डिकोड होकर अस्थायी मेमोरी में रहती हैं; Holi सर्वर को बाइट, नाम, प्रीव्यू या सेटिंग नहीं भेजी जाती।"], ["आउटपुट और मेटाडेटा", "एक्सपोर्ट कैनवस पिक्सेल से नया एनकोड होता है; EXIF, GPS, टिप्पणी, थंबनेल और नाम कॉपी नहीं होते।"], ["ब्राउज़र स्टोरेज", "इमेज सेव नहीं होतीं; थीम और भाषा पसंद लोकल स्टोरेज में रह सकती हैं।"], ["नेटवर्क", "ऐप Cloudflare से लोड होता है; वह IP, समय, पथ, ट्रैफ़िक और रूटिंग/सुरक्षा मेटाडेटा प्रोसेस कर सकता है।"]], back: "Holi Image पर वापस",
  },
  ar: {
    title: "Holi Image — مساحة صور خاصة", description: "حسّن الصور وغيّر حجمها واقتصّها وحوّلها محلياً دون نسخ بياناتها الوصفية.", eyebrow: "مساحة واحدة · خمس عمليات", headline: "عدّل الصور من دون تسليمها.", intro: "افتح عدة صور واضبطها وقارن النتيجة في مساحة واحدة ثم صدّرها.", localBadge: "معالجة محلية", workspaceLabel: "مساحة الصور", dropTitle: "أفلت الصور هنا", dropHelp: "تبقى في علامة التبويب ولا تُرفع عند اختيارها.", chooseImages: "اختر الصور", supported: "JPEG وPNG وWebP · عدة ملفات", files: "الصور", clear: "مسح", emptyQueue: "قائمة الصور فارغة.", original: "الأصل", result: "النتيجة", previewEmpty: "اختر صورة لبدء المقارنة.",
    modes: { optimize: { label: "تحسين", description: "وازن بين الجودة والحجم." }, resize: { label: "تغيير الحجم", description: "حدد أبعاد البكسل بدقة." }, crop: { label: "اقتصاص", description: "اقتصاص مركزي بنسبة مفيدة." }, convert: { label: "تحويل", description: "صدّر JPEG أو PNG أو WebP." }, clean: { label: "تنظيف", description: "أنشئ نسخة جديدة من البكسلات." } }, quality: "الجودة", width: "العرض", height: "الارتفاع", lockRatio: "حفظ النسبة", cropRatio: "نسبة الاقتصاص", format: "صيغة الإخراج", originalFormat: "حفظ الأصل", reset: "إعادة الإعدادات", downloadCurrent: "تنزيل الصورة", downloadAll: "تنزيل الكل (.zip)", ready: "جاهز", processing: "جارٍ المعالجة…", failed: "تعذرت معالجة الصورة.", cleanNote: "يُعاد ترميز كل تصدير من البكسلات. لا تنسخ Holi بيانات EXIF أو GPS أو التعليقات أو الاسم الأصلي.", sourceLabel: "المصدر", outputLabel: "التصدير",
    privacyTitle: "ملخص الخصوصية", privacySummary: "تُعالج الصور في هذا المتصفح. يمكن لـCloudflare رؤية IP ووقت الوصول، لكن Holi لا يرفع الصور.", details: "تفاصيل الخصوصية", privacyFacts: [["الصور", "تبقى الصور والمعاينات في ذاكرة علامة التبويب.", "local"], ["المعالجة", "يستخدم تغيير الحجم والاقتصاص والتحويل واجهات المتصفح.", "local"], ["التنزيل", "لا يغادر الملف إلا عندما تنزله.", "local"], ["الاستضافة", "قد تعالج Cloudflare عنوان IP والوقت والمسار والحركة والتوجيه.", "connected"]],
    explainerTitle: "أداة صور واحدة، لا متاهة أدوات صغيرة", explainer: "تشترك العمليات في القائمة والمعاينة والإعدادات والتصدير.", features: [["تحسين ومقارنة", "اضبط الجودة وشاهد الحجم قبل التنزيل."], ["تغيير الحجم والاقتصاص", "احفظ النسبة أو اختر مربعاً أو عمودياً أو أفقياً أو عريضاً."], ["تحويل وتنظيف", "أنشئ JPEG أو PNG أو WebP دون نسخ بيانات المصدر."]], faqTitle: "أسئلة شائعة", faqs: [["هل تُرفع صوري؟", "لا. الاختيار والتحرير والترميز في المتصفح؛ تتلقى Cloudflare بيانات الاتصال العادية."], ["هل يزيل التنظيف كل أثر؟", "لا تُنسخ البيانات الوصفية، لكن قد تحمل البكسلات معلومات تعريفية."], ["لماذا يكبر الملف؟", "PNG بلا فقد؛ غالباً يكون JPEG أو WebP بجودة أقل أصغر للصور."]],
    privacyPageTitle: "الخصوصية في Holi Image", privacyPageIntro: "هذا هو تدفق البيانات المطبق في مساحة الصور.", privacySections: [["الإدخال والذاكرة", "تُفك الصور داخل علامة التبويب وتبقى في ذاكرة مؤقتة؛ لا ترسل Holi البايتات أو الأسماء أو المعاينات أو الإعدادات لخادمها."], ["الإخراج والبيانات", "يُرمز التصدير من بكسلات canvas ولا ينسخ EXIF أو GPS أو التعليقات أو المصغرات أو الأسماء."], ["تخزين المتصفح", "لا تحفظ الصور؛ قد تبقى تفضيلات السمة واللغة محلياً."], ["الشبكة", "يُحمّل التطبيق من Cloudflare التي قد تعالج IP والوقت والمسار والحركة وبيانات التوجيه أو الأمان."]], back: "العودة إلى Holi Image",
  },
  bn: {
    title: "Holi Image — ব্যক্তিগত ইমেজ ওয়ার্কস্পেস", description: "ব্রাউজারে ছবি অপ্টিমাইজ, রিসাইজ, ক্রপ, কনভার্ট এবং মেটাডেটা কপি না করে এক্সপোর্ট করুন।", eyebrow: "এক ওয়ার্কস্পেস · পাঁচ কাজ", headline: "ছবি গড়ুন, হস্তান্তর নয়।", intro: "একাধিক ছবি খুলে একই জায়গায় তুলনা করুন এবং প্রস্তুত হলে এক্সপোর্ট করুন।", localBadge: "লোকাল প্রসেসিং", workspaceLabel: "ইমেজ ওয়ার্কস্পেস", dropTitle: "এখানে ছবি ফেলুন", dropHelp: "ছবি এই ট্যাবেই থাকে; নির্বাচন করলে আপলোড হয় না।", chooseImages: "ছবি বাছুন", supported: "JPEG, PNG ও WebP · একাধিক ফাইল", files: "ছবি", clear: "পরিষ্কার", emptyQueue: "ছবির তালিকা খালি।", original: "মূল", result: "ফলাফল", previewEmpty: "তুলনার জন্য ছবি বাছুন।",
    modes: { optimize: { label: "অপ্টিমাইজ", description: "মান ও সাইজের ভারসাম্য।" }, resize: { label: "রিসাইজ", description: "নির্দিষ্ট পিক্সেল মাপ দিন।" }, crop: { label: "ক্রপ", description: "প্রয়োজনীয় অনুপাতে কেন্দ্র থেকে কাটুন।" }, convert: { label: "কনভার্ট", description: "JPEG, PNG বা WebP এক্সপোর্ট।" }, clean: { label: "ক্লিন", description: "নতুন শুধু-পিক্সেল কপি বানান।" } }, quality: "মান", width: "প্রস্থ", height: "উচ্চতা", lockRatio: "অনুপাত রাখুন", cropRatio: "ক্রপ অনুপাত", format: "আউটপুট ফরম্যাট", originalFormat: "মূল রাখুন", reset: "সেটিং রিসেট", downloadCurrent: "ছবি ডাউনলোড", downloadAll: "সব ডাউনলোড (.zip)", ready: "প্রস্তুত", processing: "প্রক্রিয়াকরণ…", failed: "ছবি প্রক্রিয়া করা যায়নি।", cleanNote: "প্রতিটি এক্সপোর্ট পিক্সেল থেকে নতুন করে এনকোড হয়। Holi EXIF, GPS, মন্তব্য বা মূল নাম কপি করে না।", sourceLabel: "উৎস", outputLabel: "এক্সপোর্ট",
    privacyTitle: "গোপনীয়তার সারাংশ", privacySummary: "ছবি এই ব্রাউজারেই প্রক্রিয়া হয়। Cloudflare IP ও সময় দেখতে পারে, কিন্তু Holi ছবি আপলোড করে না।", details: "গোপনীয়তার বিস্তারিত", privacyFacts: [["ছবি", "ছবি ও প্রিভিউ এই ট্যাবের মেমোরিতে থাকে।", "local"], ["প্রক্রিয়াকরণ", "রিসাইজ, ক্রপ, কনভার্ট ও এনকোড ব্রাউজার API দিয়ে হয়।", "local"], ["ডাউনলোড", "আপনি ডাউনলোড করলেই ফাইল বাইরে যায়।", "local"], ["হোস্টিং", "Cloudflare IP, সময়, পাথ, ট্রাফিক ও রাউটিং ডেটা প্রক্রিয়া করতে পারে।", "connected"]],
    explainerTitle: "অনেক ছোট টুল নয়, একটি ইমেজ টুল", explainer: "সব কাজ একই তালিকা, প্রিভিউ, সেটিং ও এক্সপোর্ট পাইপলাইন ব্যবহার করে।", features: [["অপ্টিমাইজ ও তুলনা", "ডাউনলোডের আগে মান ও নতুন সাইজ দেখুন।"], ["রিসাইজ ও ক্রপ", "অনুপাত রাখুন বা বিভিন্ন ক্রপ বাছুন।"], ["কনভার্ট ও ক্লিন", "উৎস মেটাডেটা ছাড়া JPEG, PNG বা WebP তৈরি করুন।"]], faqTitle: "সাধারণ প্রশ্ন", faqs: [["ছবি কি আপলোড হয়?", "না। নির্বাচন, সম্পাদনা ও এনকোড ব্রাউজারে হয়; Cloudflare সাধারণ সংযোগ মেটাডেটা পায়।"], ["Clean কি সব চিহ্ন মুছে দেয়?", "উৎস মেটাডেটা কপি হয় না; দৃশ্যমান পিক্সেলে পরিচয় তথ্য থাকতে পারে।"], ["ফাইল বড় কেন হয়?", "PNG lossless; ছবির জন্য কম মানের JPEG বা WebP সাধারণত ছোট।"]],
    privacyPageTitle: "Holi Image-এর গোপনীয়তা", privacyPageIntro: "এটি ইমেজ ওয়ার্কস্পেসের বাস্তব ডেটা প্রবাহ।", privacySections: [["ইনপুট ও মেমোরি", "ফাইল এই ট্যাবে ডিকোড হয়ে অস্থায়ী মেমোরিতে থাকে; Holi সার্ভারে বাইট, নাম, প্রিভিউ বা সেটিং যায় না।"], ["আউটপুট ও মেটাডেটা", "ক্যানভাস পিক্সেল থেকে নতুন এক্সপোর্ট হয়; EXIF, GPS, মন্তব্য, থাম্বনেইল বা নাম কপি হয় না।"], ["ব্রাউজার স্টোরেজ", "ছবি স্থায়ী হয় না; থিম ও ভাষা পছন্দ লোকাল স্টোরেজে থাকতে পারে।"], ["নেটওয়ার্ক", "অ্যাপ Cloudflare থেকে লোড হয়; তারা IP, সময়, পাথ, ট্রাফিক ও রাউটিং/নিরাপত্তা তথ্য প্রক্রিয়া করতে পারে।"]], back: "Holi Image-এ ফিরুন",
  },
  pt: {
    title: "Holi Image — espaço privado de imagens", description: "Otimize, redimensione, recorte, converta e evite copiar metadados de imagens localmente.", eyebrow: "Um espaço · cinco operações", headline: "Transforme imagens sem entregá-las.", intro: "Abra várias imagens, ajuste e compare em um só espaço e exporte quando estiver pronto.", localBadge: "Processamento local", workspaceLabel: "Espaço de imagens", dropTitle: "Solte imagens aqui", dropHelp: "Elas ficam nesta aba; escolher um arquivo não faz upload.", chooseImages: "Escolher imagens", supported: "JPEG, PNG e WebP · múltiplos arquivos", files: "Imagens", clear: "Limpar", emptyQueue: "A fila está vazia.", original: "Original", result: "Resultado", previewEmpty: "Escolha uma imagem para comparar.",
    modes: { optimize: { label: "Otimizar", description: "Equilibre qualidade e tamanho." }, resize: { label: "Redimensionar", description: "Defina dimensões exatas." }, crop: { label: "Recortar", description: "Recorte central em proporção útil." }, convert: { label: "Converter", description: "Exporte JPEG, PNG ou WebP." }, clean: { label: "Limpar", description: "Crie uma cópia nova só de pixels." } }, quality: "Qualidade", width: "Largura", height: "Altura", lockRatio: "Manter proporção", cropRatio: "Proporção do recorte", format: "Formato de saída", originalFormat: "Manter original", reset: "Redefinir ajustes", downloadCurrent: "Baixar imagem", downloadAll: "Baixar todas (.zip)", ready: "Pronto", processing: "Processando…", failed: "Não foi possível processar.", cleanNote: "Cada exportação é recodificada dos pixels. A Holi não copia EXIF, GPS, comentários nem o nome original.", sourceLabel: "Origem", outputLabel: "Exportação",
    privacyTitle: "Resumo de privacidade", privacySummary: "As imagens são processadas neste navegador. A Cloudflare pode ver IP e horário, mas a Holi não envia as imagens.", details: "Detalhes de privacidade", privacyFacts: [["Imagens", "Imagens e prévias ficam na memória desta aba.", "local"], ["Processamento", "Redimensionamento, recorte, conversão e codificação usam APIs do navegador.", "local"], ["Downloads", "O arquivo só sai quando você o baixa.", "local"], ["Hospedagem", "A Cloudflare pode processar IP, horário, caminho, volume e roteamento.", "connected"]],
    explainerTitle: "Uma ferramenta de imagens, não um labirinto", explainer: "As operações compartilham fila, prévia, ajustes e exportação.", features: [["Otimize e compare", "Veja qualidade e novo tamanho antes de baixar."], ["Redimensione e recorte", "Mantenha proporções ou use recortes comuns."], ["Converta e limpe", "Crie JPEG, PNG ou WebP sem copiar metadados da origem."]], faqTitle: "Perguntas comuns", faqs: [["Minhas imagens são enviadas?", "Não. Seleção, edição e codificação ocorrem no navegador; a Cloudflare recebe metadados normais da página."], ["Limpar apaga qualquer rastro?", "Metadados não são copiados, mas os pixels visíveis ainda podem identificar algo."], ["Por que o arquivo aumenta?", "PNG é sem perdas; JPEG ou WebP com qualidade menor costuma ser menor para fotos."]],
    privacyPageTitle: "Privacidade no Holi Image", privacyPageIntro: "Este é o fluxo de dados implementado no espaço de imagens.", privacySections: [["Entrada e memória", "Arquivos são decodificados nesta aba e ficam em memória volátil; bytes, nomes, prévias e ajustes não são enviados à Holi."], ["Saída e metadados", "Exportações são recodificadas dos pixels; EXIF, GPS, comentários, miniaturas e nomes não são copiados."], ["Armazenamento", "Imagens não são persistidas; tema e idioma podem ficar no armazenamento local."], ["Rede", "O aplicativo é carregado pela Cloudflare, que pode processar IP, horário, caminho, volume e metadados de roteamento ou segurança."]], back: "Voltar ao Holi Image",
  },
};

export function getImageCopy(lang: string): ImageCopy {
  const locale = SUPPORTED_LANGS.includes(lang as LanguageCode) ? lang as LanguageCode : "en";
  return copy[locale];
}
