[workspace]
resolver = "2"
members = [
  "crates/core/holi-p2p",
  "crates/core/holi-qr",
  "crates/wasm/wasm-core",
  "crates/wasm/wasm-crypto",
  "crates/wasm/wasm-p2p",
  "crates/wasm/wasm-qr",
  "crates/wasm/wasm-qr-svg",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
