import type { LanguageCode } from "@holi/configs/i18n";

const copy = {
  en: ["Privacy summary", "QR content and images are processed on your device. Cloudflare can observe your IP and access time.", "Details", [["Processing", "Generation, styling, scanning, and export run in this browser.", "local"], ["Files", "Images you choose are not uploaded to Holi to create the QR code.", "local"], ["Persistence", "Preferences may remain locally; your browser controls exported downloads.", "local"], ["Style links", "A style link carries the style in the URL fragment (#), which browsers never send to servers; the QR content is not included.", "local"], ["Hosting", "Cloudflare may process IP, time, requested path, traffic volume, and routing data.", "connected"]]],
  es: ["Resumen de privacidad", "El contenido y las imágenes del QR se procesan en tu dispositivo. Cloudflare puede conocer tu IP y horario de acceso.", "Detalles", [["Procesamiento", "La generación, estilos, escaneo y exportación ocurren en este navegador.", "local"], ["Archivos", "Las imágenes que eliges no se suben a Holi para crear el QR.", "local"], ["Persistencia", "Las preferencias pueden permanecer localmente; las descargas las controla tu navegador.", "local"], ["Enlaces de estilo", "Un enlace de estilo lleva el estilo en el fragmento (#) de la URL, que los navegadores nunca envían al servidor; el contenido del QR no se incluye.", "local"], ["Alojamiento", "Cloudflare puede procesar IP, horario, ruta solicitada, volumen y datos de enrutamiento.", "connected"]]],
  zh: ["隐私摘要", "QR 内容和图片在你的设备上处理。Cloudflare 可能看到你的 IP 和访问时间。", "详情", [["处理", "生成、样式、扫描和导出都在此浏览器中运行。", "local"], ["文件", "你选择的图片不会上传到 Holi 来创建 QR 码。", "local"], ["持久化", "偏好设置可能保留在本地；导出下载由浏览器控制。", "local"], ["样式链接", "样式链接把样式放在 URL 的 # 片段中，浏览器不会把它发送给服务器；二维码内容不会包含在内。", "local"], ["托管", "Cloudflare 可能处理 IP、时间、请求路径、流量和路由数据。", "connected"]]],
  hi: ["गोपनीयता सारांश", "QR सामग्री और चित्र आपके डिवाइस पर प्रोसेस होते हैं। Cloudflare आपका IP और पहुँच का समय देख सकता है।", "विवरण", [["प्रोसेसिंग", "बनाना, शैली देना, स्कैन करना और निर्यात इसी ब्राउज़र में चलता है।", "local"], ["फ़ाइलें", "QR बनाने के लिए आपके चुने हुए चित्र Holi पर अपलोड नहीं होते।", "local"], ["स्थानीय डेटा", "प्राथमिकताएँ स्थानीय रह सकती हैं; निर्यात की गई डाउनलोड आपके ब्राउज़र के नियंत्रण में हैं।", "local"], ["स्टाइल लिंक", "स्टाइल लिंक स्टाइल को URL के # भाग में रखता है, जिसे ब्राउज़र कभी सर्वर को नहीं भेजते; QR की सामग्री इसमें शामिल नहीं होती।", "local"], ["होस्टिंग", "Cloudflare IP, समय, अनुरोधित पथ, ट्रैफ़िक मात्रा और रूटिंग डेटा प्रोसेस कर सकता है।", "connected"]]],
  ar: ["ملخص الخصوصية", "تُعالج محتويات QR وصوره على جهازك. قد ترى Cloudflare عنوان IP ووقت الوصول.", "التفاصيل", [["المعالجة", "يحدث الإنشاء والتنسيق والمسح والتصدير داخل هذا المتصفح.", "local"], ["الملفات", "لا تُرفع الصور التي تختارها إلى Holi لإنشاء رمز QR.", "local"], ["الاحتفاظ", "قد تبقى التفضيلات محليًا؛ ويتحكم متصفحك في التنزيلات المصدرة.", "local"], ["روابط الأنماط", "يحمل رابط النمط النمطَ في جزء # من عنوان URL الذي لا ترسله المتصفحات إلى الخوادم أبدًا؛ ولا يتضمن محتوى رمز QR.", "local"], ["الاستضافة", "قد تعالج Cloudflare عنوان IP والوقت والمسار المطلوب وحجم البيانات ومعلومات التوجيه.", "connected"]]],
  bn: ["গোপনীয়তার সারাংশ", "QR কনটেন্ট ও ছবি আপনার ডিভাইসে প্রক্রিয়া হয়। Cloudflare আপনার IP ও প্রবেশের সময় দেখতে পারে।", "বিস্তারিত", [["প্রক্রিয়াকরণ", "তৈরি, স্টাইল, স্ক্যান ও এক্সপোর্ট এই ব্রাউজারেই চলে।", "local"], ["ফাইল", "QR তৈরি করতে আপনার নির্বাচিত ছবি Holi-তে আপলোড হয় না।", "local"], ["স্থানীয় তথ্য", "পছন্দগুলো স্থানীয়ভাবে থাকতে পারে; এক্সপোর্ট করা ডাউনলোড আপনার ব্রাউজার নিয়ন্ত্রণ করে।", "local"], ["স্টাইল লিংক", "স্টাইল লিংক স্টাইলটি URL-এর # অংশে রাখে, যা ব্রাউজার কখনো সার্ভারে পাঠায় না; QR-এর কনটেন্ট এতে থাকে না।", "local"], ["হোস্টিং", "Cloudflare IP, সময়, অনুরোধ করা পথ, ট্রাফিকের পরিমাণ ও রাউটিং ডেটা প্রক্রিয়া করতে পারে।", "connected"]]],
  pt: ["Resumo de privacidade", "O conteúdo e as imagens do QR são processados no seu dispositivo. A Cloudflare pode observar seu IP e horário de acesso.", "Detalhes", [["Processamento", "Geração, estilos, leitura e exportação acontecem neste navegador.", "local"], ["Arquivos", "As imagens escolhidas não são enviadas à Holi para criar o QR.", "local"], ["Persistência", "As preferências podem permanecer localmente; seu navegador controla os downloads exportados.", "local"], ["Links de estilo", "Um link de estilo leva o estilo no fragmento (#) da URL, que os navegadores nunca enviam ao servidor; o conteúdo do QR não é incluído.", "local"], ["Hospedagem", "A Cloudflare pode processar IP, horário, caminho solicitado, volume de tráfego e dados de roteamento.", "connected"]]],
} as const;

export function getQrPrivacy(lang: string) {
  const locale = (lang in copy ? lang : "en") as LanguageCode;
  const [title, summary, detailsLabel, facts] = copy[locale];
  return { id: "qr-privacy", title, summary, detailsLabel, facts: facts.map(([label, value, tone]) => ({ label, value, tone })) };
}
