export const PRODUCT_SHELL_COPY = {
  en: {
    configuration: "configuration",
    configurationTitle: "Configuration",
    configurationEyebrow: "Local preferences",
    configurationLead: "These preferences stay in this browser and do not require an account.",
    closeConfiguration: "Close configuration",
    appearance: "Appearance",
    theme: "Theme",
    themeHint: "Applies on this device",
    auto: "auto",
    light: "light",
    dark: "dark",
    language: "Language",
    languageHint: "Only complete translations are listed",
    navigation: "Navigation",
    home: "Home",
    moreTools: "More tools",
    papers: "Papers",
    versionsTitle: "Versions",
    currentVersion: "Current",
    closeVersions: "Close versions",
    supportEyebrow: "Keep Holi available",
    supportTitle: "Support independent tools",
    supportBody: "Donations help cover hosting and development without making accounts or remote storage mandatory.",
    donate: "Donate",
    donateBody: "If Holi.tools helps you, you can support its continued development here:",
    support: "Support",
    supportSuggestions: "Support & suggestions",
    supportBodyShort: "For support, bug reports, or suggestions:",
    contact: "Contact",
    email: "Email",
    sourceCode: "Source code",
    privacy: "privacy",
    privacySummary: "Privacy summary",
    privacyEyebrow: "Privacy at a glance",
    closePrivacy: "Close privacy information",
    about: "About",
    aboutFallback: "A web-first, local-first Holi tool with legible privacy.",
    privacyDetails: "Complete privacy details",
    explore: "Explore Holi.tools",
    session: "Session",
    sessionValue: "No account · local preference",
    menu: "Menu",
    close: "Close",
  },
  es: {
    configuration: "configuración",
    configurationTitle: "Configuración",
    configurationEyebrow: "Preferencias locales",
    configurationLead: "Estas preferencias se guardan únicamente en este navegador y no requieren una cuenta.",
    closeConfiguration: "Cerrar configuración",
    appearance: "Apariencia",
    theme: "Tema",
    themeHint: "Se aplica en este dispositivo",
    auto: "auto",
    light: "claro",
    dark: "oscuro",
    language: "Idioma",
    languageHint: "Sólo aparecen traducciones completas",
    navigation: "Navegación",
    home: "Inicio",
    moreTools: "Más herramientas",
    papers: "Artículos",
    versionsTitle: "Versiones",
    currentVersion: "Actual",
    closeVersions: "Cerrar versiones",
    supportEyebrow: "Mantén Holi disponible",
    supportTitle: "Apoya herramientas independientes",
    supportBody: "Las donaciones ayudan a cubrir alojamiento y desarrollo sin volver obligatorias las cuentas ni el almacenamiento remoto.",
    donate: "Donar",
    donateBody: "Si Holi.tools te ayuda, puedes apoyar su desarrollo aquí:",
    support: "Soporte",
    supportSuggestions: "Soporte y sugerencias",
    supportBodyShort: "Para soporte, reportar errores o enviar sugerencias:",
    contact: "Contacto",
    email: "Correo",
    sourceCode: "Código fuente",
    privacy: "privacidad",
    privacySummary: "Resumen de privacidad",
    privacyEyebrow: "Privacidad de un vistazo",
    closePrivacy: "Cerrar información de privacidad",
    about: "Acerca de",
    aboutFallback: "Una herramienta Holi web-first, local-first y explícita sobre su privacidad.",
    privacyDetails: "Detalles completos de privacidad",
    explore: "Explorar Holi.tools",
    session: "Sesión",
    sessionValue: "Sin cuenta · preferencia local",
    menu: "Menú",
    close: "Cerrar",
  },
  zh: {
    configuration: "设置",
    configurationTitle: "设置",
    configurationEyebrow: "本地偏好",
    configurationLead: "这些偏好仅保存在此浏览器中，无需账户。",
    closeConfiguration: "关闭设置",
    appearance: "外观",
    theme: "主题",
    themeHint: "应用于此设备",
    auto: "自动",
    light: "浅色",
    dark: "深色",
    language: "语言",
    languageHint: "仅列出完整翻译",
    navigation: "导航",
    home: "首页",
    moreTools: "更多工具",
    papers: "文章",
    versionsTitle: "版本",
    currentVersion: "当前",
    closeVersions: "关闭版本",
    supportEyebrow: "让 Holi 持续可用",
    supportTitle: "支持独立工具",
    supportBody: "捐赠用于支付托管和开发费用，同时不强制要求账户或远程存储。",
    donate: "捐赠",
    donateBody: "如果 Holi.tools 对你有帮助，可以在这里支持持续开发：",
    support: "支持",
    supportSuggestions: "支持与建议",
    supportBodyShort: "如需支持、报告错误或提出建议：",
    contact: "联系",
    email: "电子邮件",
    sourceCode: "源代码",
    privacy: "隐私",
    privacySummary: "隐私摘要",
    privacyEyebrow: "隐私概览",
    closePrivacy: "关闭隐私信息",
    about: "关于",
    aboutFallback: "一个网页优先、本地优先且隐私说明清晰的 Holi 工具。",
    privacyDetails: "完整隐私详情",
    explore: "浏览 Holi.tools",
    session: "会话",
    sessionValue: "无需账户 · 本地偏好",
    menu: "菜单",
    close: "关闭",
  },
  hi: {
    configuration: "सेटिंग्स",
    configurationTitle: "सेटिंग्स",
    configurationEyebrow: "स्थानीय प्राथमिकताएँ",
    configurationLead: "ये प्राथमिकताएँ केवल इस ब्राउज़र में रहती हैं और खाते की आवश्यकता नहीं है।",
    closeConfiguration: "सेटिंग्स बंद करें",
    appearance: "रूप",
    theme: "थीम",
    themeHint: "इस डिवाइस पर लागू",
    auto: "स्वतः",
    light: "हल्का",
    dark: "गहरा",
    language: "भाषा",
    languageHint: "केवल पूर्ण अनुवाद दिखते हैं",
    navigation: "नेविगेशन",
    home: "मुखपृष्ठ",
    moreTools: "और टूल",
    papers: "लेख",
    versionsTitle: "संस्करण",
    currentVersion: "वर्तमान",
    closeVersions: "संस्करण बंद करें",
    supportEyebrow: "Holi को उपलब्ध रखें",
    supportTitle: "स्वतंत्र टूल का समर्थन करें",
    supportBody: "दान होस्टिंग और विकास का खर्च उठाते हैं, बिना खाते या दूरस्थ स्टोरेज को अनिवार्य बनाए।",
    donate: "दान करें",
    donateBody: "यदि Holi.tools आपके काम आता है, तो आप यहाँ इसके विकास का समर्थन कर सकते हैं:",
    support: "सहायता",
    supportSuggestions: "सहायता और सुझाव",
    supportBodyShort: "सहायता, बग रिपोर्ट या सुझाव के लिए:",
    contact: "संपर्क",
    email: "ईमेल",
    sourceCode: "स्रोत कोड",
    privacy: "गोपनीयता",
    privacySummary: "गोपनीयता सारांश",
    privacyEyebrow: "एक नज़र में गोपनीयता",
    closePrivacy: "गोपनीयता जानकारी बंद करें",
    about: "परिचय",
    aboutFallback: "स्पष्ट गोपनीयता वाला वेब-प्रथम, स्थानीय-प्रथम Holi टूल।",
    privacyDetails: "पूरी गोपनीयता जानकारी",
    explore: "Holi.tools देखें",
    session: "सत्र",
    sessionValue: "खाता नहीं · स्थानीय प्राथमिकता",
    menu: "मेनू",
    close: "बंद करें",
  },
  ar: {
    configuration: "الإعدادات",
    configurationTitle: "الإعدادات",
    configurationEyebrow: "تفضيلات محلية",
    configurationLead: "تُحفظ هذه التفضيلات في هذا المتصفح فقط ولا تتطلب حساباً.",
    closeConfiguration: "إغلاق الإعدادات",
    appearance: "المظهر",
    theme: "السمة",
    themeHint: "تُطبّق على هذا الجهاز",
    auto: "تلقائي",
    light: "فاتح",
    dark: "داكن",
    language: "اللغة",
    languageHint: "تظهر الترجمات المكتملة فقط",
    navigation: "التنقل",
    home: "الرئيسية",
    moreTools: "أدوات أخرى",
    papers: "مقالات",
    versionsTitle: "الإصدارات",
    currentVersion: "الحالي",
    closeVersions: "إغلاق الإصدارات",
    supportEyebrow: "ساعد في بقاء Holi متاحاً",
    supportTitle: "ادعم الأدوات المستقلة",
    supportBody: "تساعد التبرعات في تغطية الاستضافة والتطوير دون فرض الحسابات أو التخزين البعيد.",
    donate: "تبرع",
    donateBody: "إذا كانت Holi.tools مفيدة لك، يمكنك دعم استمرار تطويرها هنا:",
    support: "الدعم",
    supportSuggestions: "الدعم والاقتراحات",
    supportBodyShort: "للدعم أو الإبلاغ عن الأخطاء أو إرسال اقتراحات:",
    contact: "اتصال",
    email: "البريد الإلكتروني",
    sourceCode: "الشيفرة المصدرية",
    privacy: "الخصوصية",
    privacySummary: "ملخص الخصوصية",
    privacyEyebrow: "الخصوصية في لمحة",
    closePrivacy: "إغلاق معلومات الخصوصية",
    about: "حول",
    aboutFallback: "أداة Holi للويب أولاً والعمل المحلي أولاً مع خصوصية واضحة.",
    privacyDetails: "تفاصيل الخصوصية الكاملة",
    explore: "استكشف Holi.tools",
    session: "الجلسة",
    sessionValue: "بلا حساب · تفضيل محلي",
    menu: "القائمة",
    close: "إغلاق",
  },
  bn: {
    configuration: "সেটিংস",
    configurationTitle: "সেটিংস",
    configurationEyebrow: "স্থানীয় পছন্দ",
    configurationLead: "এই পছন্দগুলো শুধু এই ব্রাউজারে থাকে এবং কোনো অ্যাকাউন্ট লাগে না।",
    closeConfiguration: "সেটিংস বন্ধ করুন",
    appearance: "চেহারা",
    theme: "থিম",
    themeHint: "এই ডিভাইসে প্রযোজ্য",
    auto: "স্বয়ংক্রিয়",
    light: "হালকা",
    dark: "গাঢ়",
    language: "ভাষা",
    languageHint: "শুধু সম্পূর্ণ অনুবাদ দেখানো হয়",
    navigation: "নেভিগেশন",
    home: "হোম",
    moreTools: "আরও টুল",
    papers: "প্রবন্ধ",
    versionsTitle: "সংস্করণ",
    currentVersion: "বর্তমান",
    closeVersions: "সংস্করণ বন্ধ করুন",
    supportEyebrow: "Holi সচল রাখুন",
    supportTitle: "স্বাধীন টুল সমর্থন করুন",
    supportBody: "অ্যাকাউন্ট বা রিমোট স্টোরেজ বাধ্যতামূলক না করেই অনুদান হোস্টিং ও উন্নয়নের খরচ মেটায়।",
    donate: "অনুদান",
    donateBody: "Holi.tools কাজে লাগলে এখানে এর উন্নয়ন সমর্থন করতে পারেন:",
    support: "সহায়তা",
    supportSuggestions: "সহায়তা ও পরামর্শ",
    supportBodyShort: "সহায়তা, ত্রুটি প্রতিবেদন বা পরামর্শের জন্য:",
    contact: "যোগাযোগ",
    email: "ইমেইল",
    sourceCode: "সোর্স কোড",
    privacy: "গোপনীয়তা",
    privacySummary: "গোপনীয়তার সারাংশ",
    privacyEyebrow: "এক নজরে গোপনীয়তা",
    closePrivacy: "গোপনীয়তার তথ্য বন্ধ করুন",
    about: "পরিচিতি",
    aboutFallback: "স্পষ্ট গোপনীয়তাসহ ওয়েব-প্রথম, লোকাল-প্রথম Holi টুল।",
    privacyDetails: "সম্পূর্ণ গোপনীয়তার তথ্য",
    explore: "Holi.tools দেখুন",
    session: "সেশন",
    sessionValue: "অ্যাকাউন্ট নেই · স্থানীয় পছন্দ",
    menu: "মেনু",
    close: "বন্ধ করুন",
  },
  pt: {
    configuration: "configuração",
    configurationTitle: "Configuração",
    configurationEyebrow: "Preferências locais",
    configurationLead: "Estas preferências ficam apenas neste navegador e não exigem uma conta.",
    closeConfiguration: "Fechar configuração",
    appearance: "Aparência",
    theme: "Tema",
    themeHint: "Aplicado neste dispositivo",
    auto: "automático",
    light: "claro",
    dark: "escuro",
    language: "Idioma",
    languageHint: "Apenas traduções completas são listadas",
    navigation: "Navegação",
    home: "Início",
    moreTools: "Mais ferramentas",
    papers: "Artigos",
    versionsTitle: "Versões",
    currentVersion: "Atual",
    closeVersions: "Fechar versões",
    supportEyebrow: "Mantenha a Holi disponível",
    supportTitle: "Apoie ferramentas independentes",
    supportBody: "As doações ajudam a cobrir hospedagem e desenvolvimento sem tornar contas ou armazenamento remoto obrigatórios.",
    donate: "Doar",
    donateBody: "Se a Holi.tools ajuda você, apoie a continuidade do desenvolvimento aqui:",
    support: "Suporte",
    supportSuggestions: "Suporte e sugestões",
    supportBodyShort: "Para suporte, relatos de erros ou sugestões:",
    contact: "Contato",
    email: "E-mail",
    sourceCode: "Código-fonte",
    privacy: "privacidade",
    privacySummary: "Resumo de privacidade",
    privacyEyebrow: "Privacidade em resumo",
    closePrivacy: "Fechar informações de privacidade",
    about: "Sobre",
    aboutFallback: "Uma ferramenta Holi web-first, local-first e clara sobre privacidade.",
    privacyDetails: "Detalhes completos de privacidade",
    explore: "Explorar Holi.tools",
    session: "Sessão",
    sessionValue: "Sem conta · preferência local",
    menu: "Menu",
    close: "Fechar",
  },
} as const;

export type ProductShellLocale = keyof typeof PRODUCT_SHELL_COPY;

export function getProductShellCopy(locale: string) {
  return PRODUCT_SHELL_COPY[locale as ProductShellLocale] ?? PRODUCT_SHELL_COPY.en;
}
