import type { LanguageCode } from "@holi/configs/i18n";

type Fact = readonly [string, string, "local" | "connected"];
type PrivacyCopy = readonly [string, string, string, readonly Fact[]];

const copy: Record<LanguageCode, PrivacyCopy> = {
  en: ["Privacy summary", "This hub does not receive your documents. Cloudflare can observe your IP, access time, and technical request metadata.", "Details", [["Content", "The hub only presents tools; it does not open or process your files.", "local"], ["Preferences", "Language, theme, recent-tool shortcuts, and cached assets may remain in this browser.", "local"], ["Hosting", "Cloudflare serves the page and may process IP, time, requested path, traffic volume, and routing data.", "connected"], ["External links", "Donation, support, and repository destinations open only when you choose them.", "connected"]]],
  es: ["Resumen de privacidad", "Esta portada no recibe tus documentos. Cloudflare puede conocer tu IP, horario y metadatos técnicos de la solicitud.", "Detalles", [["Contenido", "La portada sólo presenta las herramientas; no abre ni procesa tus archivos.", "local"], ["Preferencias", "El idioma, tema, accesos recientes y recursos en caché pueden permanecer en este navegador.", "local"], ["Alojamiento", "Cloudflare sirve la página y puede procesar IP, horario, ruta solicitada, volumen y datos de enrutamiento.", "connected"], ["Enlaces externos", "Donaciones, soporte y repositorios abren servicios externos sólo cuando tú los eliges.", "connected"]]],
  zh: ["隐私摘要", "此主页不会接收你的文档。Cloudflare 可能看到你的 IP、访问时间和技术请求元数据。", "详情", [["内容", "主页只展示工具，不会打开或处理你的文件。", "local"], ["偏好设置", "语言、主题、最近工具快捷方式和缓存资源可能保留在此浏览器中。", "local"], ["托管", "Cloudflare 提供此页面，并可能处理 IP、时间、请求路径、流量和路由数据。", "connected"], ["外部链接", "捐赠、支持和代码仓库只会在你主动选择时打开。", "connected"]]],
  hi: ["गोपनीयता सारांश", "यह हब आपके दस्तावेज़ प्राप्त नहीं करता। Cloudflare आपका IP, पहुँच का समय और तकनीकी अनुरोध मेटाडेटा देख सकता है।", "विवरण", [["सामग्री", "हब केवल टूल दिखाता है; यह आपकी फ़ाइलें खोलता या प्रोसेस नहीं करता।", "local"], ["प्राथमिकताएँ", "भाषा, थीम, हाल के टूल शॉर्टकट और कैश संसाधन इस ब्राउज़र में रह सकते हैं।", "local"], ["होस्टिंग", "Cloudflare पेज उपलब्ध कराता है और IP, समय, अनुरोधित पथ, ट्रैफ़िक मात्रा व रूटिंग डेटा प्रोसेस कर सकता है।", "connected"], ["बाहरी लिंक", "दान, सहायता और रिपॉज़िटरी केवल आपके चुनने पर खुलते हैं।", "connected"]]],
  ar: ["ملخص الخصوصية", "لا يستقبل هذا المركز مستنداتك. قد ترى Cloudflare عنوان IP ووقت الوصول والبيانات الوصفية التقنية للطلب.", "التفاصيل", [["المحتوى", "يعرض المركز الأدوات فقط ولا يفتح ملفاتك أو يعالجها.", "local"], ["التفضيلات", "قد تبقى اللغة والمظهر واختصارات الأدوات الأخيرة والموارد المؤقتة في هذا المتصفح.", "local"], ["الاستضافة", "تقدم Cloudflare الصفحة وقد تعالج عنوان IP والوقت والمسار المطلوب وحجم البيانات ومعلومات التوجيه.", "connected"], ["الروابط الخارجية", "لا تفتح روابط التبرع والدعم والمستودعات إلا عندما تختارها.", "connected"]]],
  bn: ["গোপনীয়তার সারাংশ", "এই হাব আপনার ডকুমেন্ট গ্রহণ করে না। Cloudflare আপনার IP, প্রবেশের সময় ও প্রযুক্তিগত অনুরোধের মেটাডেটা দেখতে পারে।", "বিস্তারিত", [["কনটেন্ট", "হাব শুধু টুল দেখায়; এটি আপনার ফাইল খোলে বা প্রক্রিয়া করে না।", "local"], ["পছন্দ", "ভাষা, থিম, সাম্প্রতিক টুল শর্টকাট ও ক্যাশ রিসোর্স এই ব্রাউজারে থাকতে পারে।", "local"], ["হোস্টিং", "Cloudflare পেজ পরিবেশন করে এবং IP, সময়, অনুরোধ করা পথ, ট্রাফিকের পরিমাণ ও রাউটিং ডেটা প্রক্রিয়া করতে পারে।", "connected"], ["বাহ্যিক লিংক", "অনুদান, সহায়তা ও রিপোজিটরি শুধু আপনার পছন্দে খোলে।", "connected"]]],
  pt: ["Resumo de privacidade", "Este portal não recebe seus documentos. A Cloudflare pode observar seu IP, horário de acesso e metadados técnicos da solicitação.", "Detalhes", [["Conteúdo", "O portal apenas apresenta as ferramentas; não abre nem processa seus arquivos.", "local"], ["Preferências", "Idioma, tema, atalhos recentes e recursos em cache podem permanecer neste navegador.", "local"], ["Hospedagem", "A Cloudflare entrega a página e pode processar IP, horário, caminho solicitado, volume de tráfego e dados de roteamento.", "connected"], ["Links externos", "Doações, suporte e repositórios só abrem quando você escolhe.", "connected"]]],
};

export function getMainPrivacy(lang: string) {
  const locale = (lang in copy ? lang : "en") as LanguageCode;
  const [title, summary, detailsLabel, facts] = copy[locale];
  return { id: "main-privacy", title, summary, detailsLabel, facts: facts.map(([label, value, tone]) => ({ label, value, tone })) };
}
